### ISSUE TITLE
Error when first running "vagrant up"

### ISSUE THREAD

**Issue by SteveALee** [GPII/qi-development-environments#3]
==> default: failed: [localhost] => {"checksum": "518223b44053ed4dc6235e4992b0b6e713480917", "failed": true}
==> default: msg: Could not replace file: /root/.ansible/tmp/ansible-tmp-1456265491.93-206858503772364/source to /home/vagrant/.npmrc: [Errno 26] Text file busy
==> default:
==> default: FATAL: all hosts have already failed -- aborting

I'm running on a Windows host with latest Virtualbox and Vagrant.

Perhaps a timing issue? I have i7 and SSD

**Comment by SteveALee** [comment]
I'm not sure how to recover now. I tried stopping the VM and then "vagrent up" but that failed with a different error. Probably not interesting due to previous error

**Comment by SteveALee** [comment]
This is reproducible as `vagrant destroy` followed by `vagrant up` always fails the same way.

Here is my [vars.yml](https://github.com/OpenDirective/brian/blob/master/nodejs/provisioning/vars.yml)

**Comment by avtar** [comment]
Ah this is an artifact left over from when we were using Vagrant's rsync feature for sharing files between the host and VM. We are using VirtualBox Shared Folders and in order to proceed could you please change your [nodejs_app_install_dir](https://github.com/OpenDirective/brian/blob/master/nodejs/provisioning/vars.yml#L16) path to `/home/vagrant/sync` and then recreate the VM:

```
vagrant destroy -f
vagrant up
```

I'll send a PR for this. Thanks for spotting this!

**Comment by colinbdclark** [comment]
I've merged @avtar's fix for this issue. @SteveALee, when you get a chance, can you confirm that this fixes your issue after running the commands above? Thanks both of you, it's great to see this work being used and supported!

**Comment by SteveALee** [comment]
@avtar I confirm the workaround fixed that problem but I get another one later on

@colinbdclark Thanks the latest works as the workaround

**Comment by SteveALee** [comment]
==> default: failed: [localhost] => {"changed": false, "failed": true, "rc": 1}
==> default: msg: Package at https://rpm.nodesource.com/pub/el/7/x86_64/nodejs-0.10.41-1nodesource.el7.centos.x86_64.rpm could not be installed

**Comment by SteveALee** [comment]
Best ignore that error for now, I'm getting somewhat random behaviour each time I run `vagrant up`. I suspect the very poor internet here in the middle of the countryside. Will try again tomorrow.

**Comment by SteveALee** [comment]
Now i moved the files to the project root the provisioning works just fine.
