### ISSUE TITLE
A few observations on first use

### ISSUE THREAD

**Issue by SteveALee** [GPII/qi-development-environments#4]
a fresh pair of eyes and all thet.... :)
- the folder name `nodejs` is not very helpful. Can a better name be found?
- The VM name is also not helpful. Could the project name (in vars.yml) be used in it.
- The project name comment in vars.yml could explain what it is used for
- if `nodejs_app_git_clone` is false, where on earth does it find the project source?
- I had an extra leading space in vars.ym line 20 but the error I got was for line 5 - very strange.

I haven't got that far yet but wonder if my CI tasks should be prefixed with something so they can be easily identified in the 'dashboard' list. Or are you planing a new column to identify  other projects?

**Comment by avtar** [comment]
> the folder name nodejs is not very helpful. Can a better name be found?

The motivation behind this naming scheme is that in the future we want to provide other stacks that people will be able to deploy on their computers to develop or test with. We started with Node.js since its use is prevalent among GPII projects; PHP and Java will most likely be next. 

> The VM name is also not helpful. Could the project name (in vars.yml) be used in it.

I'm not sure which name you're referring to. Could you please include a line number?

> The project name comment in vars.yml could explain what it is used for

Please refer to the [Node.js role's defaults/main.yml file](https://github.com/idi-ops/ansible-nodejs/blob/master/defaults/main.yml#L20-L24) for more thorough documentation. 

> if nodejs_app_git_clone is false, where on earth does it find the project source?

I'll need to refer to this repository's [README.md](https://github.com/GPII/qi-development-environments/blob/master/README.md#contents): 

"To get started you should copy the contents of the `nodejs` directory (excluding the README) to the top-level of your application's source code tree." 

So the source doesn't need to be fetched since the `Vagrantfile` and `provisioning` directory are part of your project's repository. 

Example repositories would be:
- https://github.com/gpii/first-discovery-server
- https://github.com/simonbates/nexus

**Comment by SteveALee** [comment]
> > the folder name nodejs is not very helpful. Can a better name be found?
> 
> The motivation behind this naming scheme is that in the future we want to provide other stacks that people will be able to deploy on their computers to develop or test with. We started with Node.js since its use is prevalent among GPII projects; PHP and Java will most likely be next

I guessed that was the case but while it makes sense in the context of this repo it may not in our projects. For example we may have other folders with nodejs content.

I suggest you call it something like `QI_nodejs` or 'CI_nodejs'.

Actually, I assume we can free rename it ourselves in our projects with out issue?

**Comment by SteveALee** [comment]
> > The VM name is also not helpful. Could the project name (in vars.yml) be used in it.
> 
> I'm not sure which name you're referring to. Could you please include a line number?

Ah I was not clear. When you run the VB control panel the QI VM appears in the list of VMs. The name is obscure to say the least :)

**Comment by SteveALee** [comment]
> > if nodejs_app_git_clone is false, where on earth does it find the project source?
> 
> "To get started you should copy the contents of the nodejs directory (excluding the README) to the top-level of your application's source code tree."
> 
> So the source doesn't need to be fetched since the Vagrantfile and provisioning directory are part of your project's repository. 

Hmm we may be speaking at cross purposes. I'm happy that the QI source is included as part of my repo. However my project code must be inside the the VM and I am assuming that it will do a `clone` to get it? Is that not the case?

**Comment by SteveALee** [comment]
I felt the readme could do wit ha few tweaks to make things clearer. Perhaps I'll do a PR when I've more understanding

**Comment by avtar** [comment]
> For example we may have other folders with nodejs content.

Just to clarify, you're only copying the contents of the `nodejs` directory to the top level of your git repository, not the directory itself. Taken from this repository's README: 

"To get started you should copy the contents of the nodejs directory (excluding the README) to the top-level of your application's source code tree."

Please take a look at these repos for examples:
- https://github.com/gpii/first-discovery-server
- https://github.com/simonbates/nexus

If you feel the README's language could use some massaging to better reflect this requirement then please send a PR. The [process for contributing to GPII repositories](https://wiki.fluidproject.org/display/fluid/Contributing+Code) mirrors the one used by the Fluid Project. 

> When you run the VB control panel the QI VM appears in the list of VMs. The name is obscure to say the least :)

Ah I see. That name is randomly generated by Vagrant.

> However my project code must be inside the the VM and I am assuming that it will do a clone to get it? Is that not the case?

By including the Vagrantfile (and the accompanying `provisioning` directory) you are letting Vagrant share your git working directory with the VM. For more information please refer to the [Synced Folders](https://www.vagrantup.com/docs/synced-folders/) section of the Vagrant documentation.

**Comment by SteveALee** [comment]
> Just to clarify, you're only copying the contents of the nodejs directory to the top level of your git repository, not the directory itself.

Ah yes, my bad 

> By including the Vagrantfile (and the accompanying provisioning directory) you are letting Vagrant share your git working directory with the VM. For more information please refer to the Synced Folders section of the Vagrant documentation.

Ah, perfect. And that answers my next question too. 

Thanks very much.

**Comment by avtar** [comment]
You're welcome :)

**Comment by SteveALee** [comment]
Seems the provider .name cane be used to set the VM name. However it starts with the project folder name (once you have the files in the right place, that is).

https://www.vagrantup.com/docs/virtualbox/configuration.html
